// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9H-Ii74rKBTSWq6urpZ8qIxhlO8aUhdI',
    appId: '1:172718830384:web:c3de459a1e08d603950ef5',
    messagingSenderId: '172718830384',
    projectId: 'flutter-treads-clone',
    authDomain: 'flutter-treads-clone.firebaseapp.com',
    storageBucket: 'flutter-treads-clone.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5SjHFH3alUs-CgY8dBRtihLeP-mdShdc',
    appId: '1:172718830384:android:cff685e6c904c2fa950ef5',
    messagingSenderId: '172718830384',
    projectId: 'flutter-treads-clone',
    storageBucket: 'flutter-treads-clone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4XbT5yDPrrZ4PbZlg8E8LtMtVNmmhAIg',
    appId: '1:172718830384:ios:3b14a5eaa781e29c950ef5',
    messagingSenderId: '172718830384',
    projectId: 'flutter-treads-clone',
    storageBucket: 'flutter-treads-clone.appspot.com',
    iosBundleId: 'com.example.flutterTreadsCloneFirebase',
  );
}
